"""empty message

Revision ID: ff80f1bf1835
Revises: 92aa22aade73
Create Date: 2018-10-29 17:27:45.354712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff80f1bf1835'
down_revision = '92aa22aade73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('migrations')
    op.drop_table('country')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('country',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('country_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('short_name', sa.VARCHAR(length=3), autoincrement=False, nullable=True),
    sa.Column('full_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='country_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('migrations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('dest_country', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('source_country', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['dest_country'], ['country.id'], name='migrations_dest_country_fkey'),
    sa.ForeignKeyConstraint(['source_country'], ['country.id'], name='migrations_source_country_fkey'),
    sa.PrimaryKeyConstraint('id', name='migrations_pkey')
    )
    # ### end Alembic commands ###
