"""empty message

Revision ID: ae9af5aa0fd3
Revises: 
Create Date: 2018-10-30 17:16:44.773940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae9af5aa0fd3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('country',
    sa.Column('short_name', sa.String(length=5), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('short_name')
    )
    op.create_table('migrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dest_country', sa.String(length=5), nullable=True),
    sa.Column('source_country', sa.String(length=5), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('total', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(length=15), nullable=True),
    sa.Column('age_range', sa.String(length=15), nullable=True),
    sa.ForeignKeyConstraint(['dest_country'], ['country.short_name'], ),
    sa.ForeignKeyConstraint(['source_country'], ['country.short_name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('migrations')
    op.drop_table('country')
    # ### end Alembic commands ###
